### ISSUE TITLE
Broken dark theme cards (brew card)

### ISSUE THREAD

**Issue by hez** [Baradoy/home_dash#20]
Looks like one of the last two prs merged broke the dark theme for brew cards (maybe others as well.) From what I can tell it is either #17 or #18.

Expected: 

<img width="350" alt="Screenshot 2024-05-25 at 15 18 00" src="https://github.com/Baradoy/home_dash/assets/244021/290c5617-21b3-4166-92ea-893696e9ef5a">

What it looks like now:

<img width="358" alt="Screenshot 2024-05-25 at 15 18 14" src="https://github.com/Baradoy/home_dash/assets/244021/224770a1-a7f6-484f-9079-ea31045d124b">

**Comment by Baradoy** [comment]
Does not seem to be reproducible.
